services:
  web:
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - PORT=3000
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  app-data:
    driver: local
