import "./globals.css";

export const metadata = {
  title: "Nischal Dahal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body data-gr-c-s-loaded="true">{children}</body>
    </html>
  );
}
